import * as Types from '../../generated/graphql-types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type MemberQueryVariables = Types.Exact<{
  bioGuideId: Types.Scalars['String'];
}>;


export type MemberQuery = { __typename?: 'Query', member?: { __typename?: 'Member', id: string, profilePictureUri?: string | null | undefined, firstName?: string | null | undefined, firstName_zh?: string | null | undefined, lastName?: string | null | undefined, lastName_zh?: string | null | undefined, nickname?: string | null | undefined, gender?: string | null | undefined, birthday?: string | null | undefined, website?: string | null | undefined, office?: string | null | undefined, phone?: string | null | undefined, cspanId?: string | null | undefined, twitterId?: string | null | undefined, facebookId?: string | null | undefined, youtubeId?: string | null | undefined, congressRoles: Array<{ __typename?: 'MemberRole', chamber: string, state: string, district?: number | null | undefined, senatorClass?: number | null | undefined, congressNumbers: Array<number>, startDate: string, endDate: string, parties: Array<{ __typename?: 'PartyRecord', party: string, startDate: string, endDate: string }> }> } | null | undefined };


export const MemberDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Member"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"bioGuideId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"member"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"bioGuideId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"bioGuideId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"profilePictureUri"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"firstName_zh"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName_zh"}},{"kind":"Field","name":{"kind":"Name","value":"nickname"}},{"kind":"Field","name":{"kind":"Name","value":"gender"}},{"kind":"Field","name":{"kind":"Name","value":"birthday"}},{"kind":"Field","name":{"kind":"Name","value":"website"}},{"kind":"Field","name":{"kind":"Name","value":"office"}},{"kind":"Field","name":{"kind":"Name","value":"phone"}},{"kind":"Field","name":{"kind":"Name","value":"cspanId"}},{"kind":"Field","name":{"kind":"Name","value":"twitterId"}},{"kind":"Field","name":{"kind":"Name","value":"facebookId"}},{"kind":"Field","name":{"kind":"Name","value":"youtubeId"}},{"kind":"Field","name":{"kind":"Name","value":"congressRoles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"chamber"}},{"kind":"Field","name":{"kind":"Name","value":"state"}},{"kind":"Field","name":{"kind":"Name","value":"district"}},{"kind":"Field","name":{"kind":"Name","value":"senatorClass"}},{"kind":"Field","name":{"kind":"Name","value":"congressNumbers"}},{"kind":"Field","name":{"kind":"Name","value":"parties"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"party"}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"endDate"}}]}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"endDate"}}]}}]}}]}}]} as unknown as DocumentNode<MemberQuery, MemberQueryVariables>;