import * as Types from '../../generated/graphql-types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type BillQueryVariables = Types.Exact<{
  billId: Types.Scalars['String'];
}>;


export type BillQuery = { __typename?: 'Query', bill?: { __typename?: 'DenormalizedBill', congress: number, billType: string, billNumber: number, introducedDate?: string | null | undefined, sponsorId: string, cosponsorsCount?: number | null | undefined, title: { __typename?: 'I18NText', zh?: string | null | undefined, en?: string | null | undefined, text?: string | null | undefined }, trackers?: Array<{ __typename?: 'BillTracker', stepName: string, selected: boolean }> | null | undefined, actions?: Array<{ __typename?: 'BillAction', description: string, date: string, chamber?: string | null | undefined }> | null | undefined, sponsor?: { __typename?: 'Member', id: string, firstName?: string | null | undefined, lastName?: string | null | undefined, nickname?: string | null | undefined, firstName_zh?: string | null | undefined, lastName_zh?: string | null | undefined } | null | undefined, cosponsors?: Array<{ __typename?: 'Member', firstName?: string | null | undefined, lastName?: string | null | undefined, firstName_zh?: string | null | undefined, lastName_zh?: string | null | undefined }> | null | undefined } | null | undefined };


export const BillDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Bill"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"billId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bill"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"billId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"congress"}},{"kind":"Field","name":{"kind":"Name","value":"billType"}},{"kind":"Field","name":{"kind":"Name","value":"billNumber"}},{"kind":"Field","name":{"kind":"Name","value":"title"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"zh"}},{"kind":"Field","name":{"kind":"Name","value":"en"}},{"kind":"Field","name":{"kind":"Name","value":"text"}}]}},{"kind":"Field","name":{"kind":"Name","value":"introducedDate"}},{"kind":"Field","name":{"kind":"Name","value":"trackers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"stepName"}},{"kind":"Field","name":{"kind":"Name","value":"selected"}}]}},{"kind":"Field","name":{"kind":"Name","value":"actions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"chamber"}}]}},{"kind":"Field","name":{"kind":"Name","value":"sponsorId"}},{"kind":"Field","name":{"kind":"Name","value":"sponsor"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"nickname"}},{"kind":"Field","name":{"kind":"Name","value":"firstName_zh"}},{"kind":"Field","name":{"kind":"Name","value":"lastName_zh"}}]}},{"kind":"Field","name":{"kind":"Name","value":"cosponsorsCount"}},{"kind":"Field","name":{"kind":"Name","value":"cosponsors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"firstName_zh"}},{"kind":"Field","name":{"kind":"Name","value":"lastName_zh"}}]}}]}}]}}]} as unknown as DocumentNode<BillQuery, BillQueryVariables>;