export default {
  brand: {
    fullName: 'US Taiwan Watch',
  },
  header: {
    subtitle: 'Promote and facilitate the understanding of the US and Taiwan relationship through grassroots Taiwanese-American opinions and analysis of international relations ',
    about: 'About',
    partners: 'Partners',
    follow: 'Follow Us',
    join: 'Join Us',
    donate: 'Donate',
    subscribe: 'Subscribe',
  },
  landing: {
    testI18n: "I18n - 中文內容",
    aboutDesc: 'US Taiwan Watch is committed to deepening Taiwan-U.S. relations, reducing the threshold of citizen diplomacy, and perfecting citizen diplomacy by reducing information asymmetry and enhancing public understanding of Taiwan-U.S. affairs and international trends. In 2022, as a team effort, US Taiwan Watch aims to "shorten the distance" between Taiwan and the U.S. With the advantage of being physically located in the United States, our team hopes to produce and broadcast more audio-visual content in the U.S. and bridge the gap between Taiwanese and American societies such that Taiwanese audiences may have a more comprehensive understanding of U.S. society, culture and diplomacy.',
    partnersDesc: "We work with blahblah",
    followDesc: "yoyoyo",
    joinDesc: 'The work and programs on US Taiwan Watch are all generated by volunteers who are passionate about learning and introducing US Taiwan relations to more people. We welcome anyone interested in advocating US Taiwan topics to join our team! We seek experienced (or just interested) volunteers in making news memos in Chinese and English, research, translation, fund-raising, and event planning. Fill out the form, and we will contact you as soon as possible!',
    joinButton: 'Sign up to be a volunteer!',
    donateDesc: 'US Taiwan Watch\'s original intention is to deepen the Taiwan-US relationship and encourage civic and public participation between the two nations. In the age of information explosion and misinformation, we still strive and dedicate ourselves to becoming the most professional and comprehensive platform for Taiwan-US relations. In order to become the bridge that brings Taiwanese and American citizens together, we appreciate any amount of donation for the operation and program making of US Taiwan Watch. If you support our intention and goals, we welcome you to donate through the below-listed methods to support us. If there\'s a particular program you wish your donation to be dedicated to(e.g.podcast, specific topic research analysis, interactive workshop, etc.), please indicate it in your donation.We devote all our work to building strong Taiwan - US relations and bridging the two nations\' citizens who value democratic values. ',
    donateButton: 'Become our donor (International) ',
    donateButtonTW: 'Become our donor (Taiwan) ',
    subscribeDesc: 'We welcome you to subscribe to our monthly "US Taiwan Watch" newsletter. The newsletter contains our analysis of selected major events that have happened in the past few weeks that we believe could shape the direction of the US-Taiwan relationship. We also publish the schedule and info of our upcoming public events in both US and Taiwan in the newsletter.',
    subscribeButton: 'Subscribe to our newsletter!',
  },
  social: {
    fb: 'Facebook is the primary platform we share our information. On this platform, we aim to debunk misinformation and bias to strengthen the US-Taiwan relationship by providing the latest news and thorough analysis of the current events and policies between the US and Taiwan.',
    ig: 'Instagram serves as our channel for community outreach and a medium for connecting with the younger crowd. We hope to build a more substantial presence in our audience by having weekly live streams and short reels to interact and share our work more creatively and succinctly.',
    tw: 'Twitter is the medium we cater for our audience in the English-speaking world. On top of providing our latest news analysis and opinions, we share Taiwanese news, culture, and experience with our English-speaking audiences interested in learning about Taiwan and its predicament on the international stage. We also aspire this can serve as a portal for our Taiwanese audience to exchange with our foreign viewers to understand the role of Taiwan in the globalized communities. ',
    yt: 'US Taiwan Watch has produced a Youtube series of 7 videos while we are touring in Washington DC. In this series, we explored the city of Washington DC, and traveled around significant US federal buildings such as Capitol Hill, the White House, and the Massachusetts Avenue Embassy Row. We also interview policy researchers and advocates in local thinktank and political organizations such as Global Taiwan Institute (GTI) and Taiwan Democratic Progressive Party Mission in the US. Moreover, we also upload our weekly podcast program on the Youtube Channel. We are also working on expanding our video platform with various and numerous new programs to engage and expose our Taiwanese audience to US political system and environment. ',
    podcast: 'Our podcast program, "US Taiwan Watch in da House," focuses on sharing our analysis of current events and policy-making between the US and Taiwan. Since our debut in April 2020, we have generated 100+ podcast episodes discussing the US-Taiwan relationship with renowned scholars, foreign diplomats, and political workers in Taiwan. On July 14, 2022, we recorded 68K downloads for our podcast program and an average of 6000 view/listen on each episode. Furthermore, the podcast program has expanded our audience group to China, Japan, Vietnam, Hong Kong, and Australia beyond Taiwan and the US.',
  }
};
